site_name: 'py-app1'
site_description: 'Main documentation for the py-app1'
repo_url: https://github.com/ricardoandre97/py-app1
edit_uri: edit/main/docs

#plugins
plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting started: 'docs/index.md'
